app:
  redis:
    host: localhost
    port: 18840
    maxIdle: 64
    maxTotal: 128
    testOnBorrow: true
    inputQueue: tas-queue-input-movimientos-cuenta-oracle
    outputQueue: pfm-preprocessor-out
