app:
  redis:
    host: localhost
    port: 18840
    maxIdle: 64
    maxTotal: 128
    testOnBorrow: true
    inputQueue: pfm-preprocessor-request
    outputQueue: pfm-preprocessor-response

server:
    port: 8085
